name: CI/CD MLflow
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
env:
  TRAIN_PATH: "MLProject/NVDA_Stock_Preprocessing/train_set"
  TEST_PATH: "MLProject/NVDA_Stock_Preprocessing/test_set"
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.3
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"
 
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install tensorflow
      
      # Clear run_id so it didn't conflict with internal mlflow run
      - name: Clear MLflow env
        run: |
          unset MLFLOW_RUN_ID
          unset MLFLOW_EXPERIMENT_ID

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/lstm_model" --name "lstm_model_nvda_stock"

      - name: List Docker Images
        run: docker images

      - name: Upload mlruns
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Tag Docker Image
        run: |
          docker tag lstm_model_nvda_stock ${{ secrets.DOCKER_HUB_USERNAME }}/lstm_model_nvda_stock:latest

      - name: Verify Docker Login & Images
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker images
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lstm_model_nvda_stock:latest